openapi: 3.0.3
info:
  title: My API - OpenAPI 3.0
  version: 0.0.1
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: Numeric ID of the user to get
        